# Generated by Django 2.1 on 2019-02-17 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('admission_number', models.IntegerField()),
                ('registration_number', models.IntegerField()),
                ('roll_number', models.IntegerField()),
                ('phone_number', models.IntegerField(max_length=10)),
                ('email_id', models.EmailField(blank=True, max_length=254, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.AcademicYear')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Semester')),
            ],
        ),
    ]
