# Generated by Django 2.1 on 2019-02-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20190218_0710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendence',
            old_name='attend',
            new_name='h1',
        ),
        migrations.RemoveField(
            model_name='attendence',
            name='hour',
        ),
        migrations.AddField(
            model_name='attendence',
            name='h2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendence',
            name='h3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendence',
            name='h4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendence',
            name='h5',
            field=models.BooleanField(default=False),
        ),
    ]
