# Generated by Django 2.1 on 2019-02-27 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20190226_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('h1', models.BooleanField(default=False)),
                ('h2', models.BooleanField(default=False)),
                ('h3', models.BooleanField(default=False)),
                ('h4', models.BooleanField(default=False)),
                ('h5', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Student')),
            ],
        ),
    ]
