# Generated by Django 2.1 on 2019-03-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_remove_notificationstudent_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default='UserDP/default.png', null=True, upload_to='UserDP/'),
        ),
    ]
