# Generated by Django 2.1 on 2019-03-04 03:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20190302_0547'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeminarAssignmentProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('abstract', models.CharField(max_length=1000)),
                ('file', models.FileField(upload_to='UserUploads/')),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default='UserDP/default.png', upload_to='UserDP/'),
        ),
    ]
