# Generated by Django 2.1 on 2019-03-04 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20190304_0355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(default='UserDP/default.png', upload_to='UserDP/')),
                ('teacher_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email_id', models.EmailField(blank=True, max_length=254, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Department')),
            ],
        ),
        migrations.AddField(
            model_name='seminarassignmentproject',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seminarassignmentproject',
            name='submited_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Teacher'),
            preserve_default=False,
        ),
    ]
