# Generated by Django 2.1 on 2019-03-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20190304_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminarassignmentproject',
            name='typ',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
