# Generated by Django 2.1 on 2019-03-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_seminarassignmentproject_typ'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendenceFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdate', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='seminarassignmentproject',
            name='typ',
            field=models.CharField(choices=[('Seminar', 'Seminar'), ('Assignment', 'Assignment'), ('Project', 'Project')], default='Seminar', max_length=20),
        ),
    ]
